openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081
  description: Generated server url
paths:
  /students/{id}:
    get:
      tags:
      - student-controller
      operationId: getStudyById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FullStudentDto"
    put:
      tags:
      - student-controller
      operationId: updateStudent
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateStudentDto"
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FullStudentDto"
  /students/admin:
    get:
      tags:
      - student-controller
      operationId: getAllStudy
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ShortStudentDto"
    post:
      tags:
      - student-controller
      operationId: createdStudy
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateStudentDto"
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FullStudentDto"
components:
  schemas:
    ApiError:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
        timestamp:
          type: string
          format: date-time
    CreateStudentDto:
      required:
      - firstName
      - lastName
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        dateOfBirth:
          type: string
          format: date-time
        phoneNumber:
          type: string
        email:
          type: string
        photoUrl:
          type: string
    FullStudentDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        dateOfBirth:
          type: string
          format: date-time
        phoneNumber:
          type: string
        email:
          type: string
        photoUrl:
          type: string
        createdAt:
          type: string
          format: date-time
    ShortStudentDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        photoUrl:
          type: string
